site_name: Papers
pages:
    - Home: index.md
    - Image Classification:
      - Introduction: imageclassif/index.md
      - SSD: imageclassif/ssd.md
      - RAM: imageclassif/ram.md
    - Image Segmentation:
      - Introduction: imageseg/index.md
    - Natural Language Processing:
      - Introduction: nlp/index.md
    - Reinforcement Learning:
      - Introduction: rl/index.md
    - Tracking:
      - Introduction: tracking/index.md
      - Online Multi-Target Tracking RNN: tracking/onlinemultitrackingRNN.md
    - Knowing your Network:
      - Why Should I Trust You ?: whyshoulditrustyou.md
    - Contributing: contributing.md