site_name: Papers

theme: readthedocs

python:
   version: 2 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math) 
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

pages:
    - Home: index.md
    - Image Classification:
      - Introduction: imageclassif/index.md
      - ImageNet Classification with Deep CNN: imageclassif/imagenet.md
      - OverFeat: imageclassif/overfeat.md
      - RAM: imageclassif/ram.md
      - CapsNet: imageclassif/capsule.md
      - VGG: imageclassif/vgg.md
      - ResNet: imageclassif/resnet.md
    - Image Detection:
      - Introduction: imagedetection/index.md
      - R-CNN: imagedetection/rcnn.md
      - Fast R-CNN: imagedetection/fastrcnn.md
      - Faster R-CNN: imagedetection/fasterrcnn.md
      - R-FCN: imagedetection/rfcn.md
      - YOLO: imagedetection/yolo.md
      - YOLOv2: imagedetection/yolov2.md
      - YOLOv3: imagedetection/yolov3.md
      - SSD: imagedetection/ssd.md
      - FSSD: imagedetection/fssd.md
      - RFB: imagedetection/rfb.md
      - Deformable Convolutional Networks: imagedetection/deformableconvolutionalnetworks.md
      - RetinaNet: imagedetection/focalloss.md
    - Image Segmentation:
      - Introduction: imageseg/index.md
      - SqueezeSeg: imageseg/squeezeseg.md
      - SqueezeSegv2: imageseg/squeezesegv2.md
    - Image Generation:
      - Introduction: imagegeneration/index.md
      - Photographic Image Synthesis with Cascaded Refinement Networks: imagegeneration/photographicimagesynthesis.md
    - Natural Language Processing:
      - Introduction: nlp/index.md
    - Reinforcement Learning:
      - Introduction: rl/index.md
    - Tracking:
      - Introduction: tracking/index.md
      - Online Multi-Target Tracking RNN: tracking/onlinemultitrackingRNN.md
      - Virtual Worlds as Proxy for Multi-Object Tracking Analysis: tracking/vkitti.md
      - SORT: tracking/sort.md
      - DeepSORT: tracking/deepsort.md
      - MaskProp: tracking/maskprop.md
    - Counting:
      - Introduction: counting/index.md
      - Highway Vehicle Counting in Compressed Domain: counting/highwayvehiclecountingcompresseddomain.md
    - Scene Graph:
      - Introduction: scenegraph/index.md
      - Image Generation From Scene Graph: scenegraph/imagegenerationfromscenegraph.md
      - Neural Motifs, Scene Graph Parsing with Global Context: scenegraph/neuralmotifparsingwithglobalcontext.md
      - Scene Graph Generation From Images: scenegraph/scenegraphgenerationfromimages.md
    - Knowing your Network:
      - Introduction: knowingyournetwork/index.md
      - Why Should I Trust You ?: knowingyournetwork/whyshoulditrustyou.md
      - ImageNet-trained CNNs are biased towards texture; increasing shape bias improves accuracy and robustness: knowingyournetwork/biastowardtextures.md
    - Flow estimation:
      - Introduction: flow/index.md
      - FlowNet: flow/flownet.md
      - FlowNet2: flow/flownet2.md
      - DSTFlow: flow/unsupervisedopticalflow.md
      - Estimating Velocity Fields on a Freeway From Low-Resolution Videos: flow/EstimatingVelocityFieldsFreewayLowResolution.md
      - Highway Traffic Information Extraction fiom Skycam MPEG Video: flow/HighwayTrafficInformationExtractionSkycamMPEGVideo.md
      - Compressed-Domain Highway Vehicle Counting by Spatial and Temporal Regression: flow/CompressedDomainHighwayVehicleCountingRegression.md
      - Traffic Congestion Estimation Using HMM Models Without Vehicle Tracking: flow/TrafficCongestionEstimationHMMModelsWithoutVehicleTracking.md
      - An algorithm to estimate mean vehicle speed from MPEG Skycam video: flow/EstimateMeanVehicleSpeedMPEGSkycam.md
      - A Semi-Automatic 2D solution for Vehicle Speed Estimation from Monocular Videos: flow/Semiautomatic2dspeedestimationmonocular.md
    - Others:
      - Introduction: others/index.md
      - CoordConv: others/coordconv.md
      - Accurate, Large Minibatch SGD:Training ImageNet in 1 Hour: others/AccurateLargeMinibatchSGD.md
    - Optimizers:
      - Introduction: optimization/index.md
      - Stochastic gradient descent: optimization/sgd.md
    - Datasets:
      - Introduction: datasets/index.md
      - Database: datasets/list.md
      - Object Counting: datasets/counting.md
      - Events: datasets/events.md
      - Forgery: datasets/forgery.md
      - Image Classification/Detection: datasets/imageclassification.md
      - Image Segmentation: datasets/imagesegmentation.md
      - NLP: datasets/nlp.md
      - RL: datasets/rl.md
      - Tracking: datasets/tracking.md
      - Graphs : datasets/scenegraph.md
    - Contributing: contributing.md