site_name: Papers

theme: readthedocs

python:
   version: 2 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math) 
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

pages:
    - Home: index.md
    - Image Classification:
      - ImageNet Classification with Deep CNN: imageclassif/imagenet.md
      - OverFeat: imageclassif/overfeat.md
      - RAM: imageclassif/ram.md
      - CapsNet: imageclassif/capsule.md
    - Image Detection:
      - R-CNN: imagedetection/rcnn.md
      - Fast R-CNN: imagedetection/fastrcnn.md
      - Faster R-CNN: imagedetection/fasterrcnn.md
      - R-FCN: imagedetection/rfcn.md
      - YOLO: imagedetection/yolo.md
      - YOLOv2: imagedetection/yolov2.md
      - YOLOv3: imagedetection/yolov3.md
      - SSD: imagedetection/ssd.md
      - FSSD: imagedetection/fssd.md
      - RFB: imagedetection/rfb.md
      - Deformable Convolutional Networks: imagedetection/deformableconvolutionalnetworks.md
    - Image Segmentation:
      - Introduction: imageseg/index.md
    - Image Generation:
      - Photographic Image Synthesis with Cascaded Refinement Networks: imagegeneration/photographicimagesynthesis.md
    - Natural Language Processing:
      - Introduction: nlp/index.md
    - Reinforcement Learning:
      - Introduction: rl/index.md
    - Tracking:
      - Online Multi-Target Tracking RNN: tracking/onlinemultitrackingRNN.md
    - Scene Graph:
      - Image Generation From Scene Graph: scenegraph/imagegenerationfromscenegraph.md
      - Neural Motifs, Scene Graph Parsing with Global Context: scenegraph/neuralmotifparsingwithglobalcontext.md
      - Scene Graph Generation From Images: scenegraph/scenegraphgenerationfromimages.md
    - Knowing your Network:
      - Why Should I Trust You ?: knowingyournetwork/whyshoulditrustyou.md
    - Others:
      - CoordConv: others/coordconv.md
    - Optimizers:
      - Introduction: optimization/index.md
      - Stochastic gradient descent: optimization/sgd.md
      - AdaGrad: optimization/adagrad.md
    - Datasets:
      - Database: datasets/list.md
      - Object Counting: datasets/counting.md
      - Events: datasets/events.md
      - Forgery: datasets/forgery.md
      - Image Classification: datasets/imageclassification.md
      - Image Segmentation: datasets/imagesegmentation.md
      - NLP: datasets/nlp.md
      - RL: datasets/rl.md
      - Tracking: datasets/tracking.md
    - Contributing: contributing.md